# Generated by Django 4.0.4 on 2022-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Airplane ID')),
                ('airplane_name', models.CharField(max_length=100, verbose_name='Airplane name')),
                ('passengers_count', models.PositiveIntegerField(verbose_name='Passengers count')),
            ],
        ),
    ]
